language: android
jdk: oraclejdk8
android:
  components:
      - tools
      - platform-tools

      - android-28
      
      - build-tools-28.0.2
before_install:
  # The following line can be removed when https://github.com/travis-ci/travis-ci/issues/8874 is resolved
  - yes | sdkmanager "platforms;android-28"
script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build
